import { Link } from "react-router-dom";
import { Layout } from "../components/Layout";
import { Badge, severityTone, statusTone } from "../components/Badge";
import { engineeringIssues } from "../data/mockData";

export function EngineeringIssues() {
  return (
    <Layout title="Engineering Issues" subtitle="Issues generated by the Innovation Architect agent">
      <div className="space-y-3">
        {engineeringIssues.map((issue) => (
          <Link
            key={issue.id}
            to={`/issues/${issue.id}`}
            className="card flex flex-col gap-2 p-5 transition-shadow hover:shadow-md sm:flex-row sm:items-center sm:justify-between"
          >
            <div>
              <div className="mb-1.5 flex items-center gap-2">
                <span className="text-xs font-bold text-accent-700">{issue.id}</span>
                <Badge tone={severityTone(issue.severity)}>{issue.severity}</Badge>
                <Badge tone={statusTone(issue.status)}>{issue.status}</Badge>
              </div>
              <p className="text-sm font-semibold text-ink-900">{issue.title}</p>
              <p className="mt-0.5 text-xs text-ink-500">{issue.component}</p>
            </div>
            <span className="text-xs text-ink-400">
              {new Date(issue.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric" })}
            </span>
          </Link>
        ))}
      </div>
    </Layout>
  );
}
